mysql:
  host: localhost
  port: 3306
  user: root
  password: root
  database: mmo_game
  db_config: charset=utf8mb4&parseTime=True&loc=Local
  table_prefix: mmo_

zap:
  director: storage/logs
  log_level: info
  encode_level: LowercaseColorLevelEncoder
  log_prefix: ""

mongodb:
  host: localhost
  port: 27017
  user: root
  password: root
  database: mmo_game
  min_pool_size: 3
  max_pool_size: 3000

server:
  host: 0.0.0.0
  port: 32510
  worker_count: 4

buffer_size: 6000
